language: php
php:
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"

before_script:
  - composer install
script:
  - bin/phpunit -c ./

notifications:
  emails:
    - issei.m7+travisci@gmail.com
  on_success: always
  on_failure: always
